spring:
  profiles:
    active: dev
---
server:
  port: 4001
spring:
  profiles: dev
  application:
    name: micrservice-congif-dev
---
server:
  port: 4002
spring:
  profiles: prod
  application:
    name: micrservice-congif-prod